apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: dev-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: tomcat-jenkins
      labels:
        app: tomcat
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: size
                  operator: NotIn
                  values:
                  - large
                  - small
      containers:
      - name: mytomcat
        image: sujatagoudar/mytomcat:1.0.5
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 128Mi
