apiVersion: v1
kind: Pod
metadata:
  name: tomcat-nginxl
  labels: 
    app: tomcat
spec:
  containers:
  - name: mytomcat
    image: sujatagoudar/mytomcat:1.0.5
    resources:
      limits:
          memory: "250Mi"
      requests:
        memory: "150Mi"
