
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: tomcat-jenkins
      labels:
        app: tomcat
    spec:
      containers:
      - name: mytomcat
        image: sujatagoudar/mytomcat:1.0.5
